name: ShellCheck Audit

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    name: Shell Script Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck with security flags
        run: |
          find . -type f -name "*.sh" | while read -r file; do
            echo "🔍 Checking $file"
            shellcheck -x --severity=style "$file"
          done
